#ifndef SOFTKEYBOARD_DLL_GLOBAL_H
#define SOFTKEYBOARD_DLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOFTKEYBOARD_DLL_LIBRARY)
#  define SOFTKEYBOARD_DLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOFTKEYBOARD_DLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOFTKEYBOARD_DLL_GLOBAL_H
