; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	E:\Young\project\myPlot\QtGuiApplication3\QtGuiApplication3\GeneratedFiles\Debug\moc_Highlighter.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG118807 DB	'C:\Qt\Qt5.9.2\5.9.2\msvc2015\include\QtCore/qmetatype.h', 00H
$SG118808 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG118809 DB	'qRegisterNormalizedMetaType', 00H
$SG120000 DB	'C:\Qt\Qt5.9.2\5.9.2\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG120001 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG120002 DB	'qRegisterNormalizedMetaType', 00H
$SG119109 DB	'C:\Qt\Qt5.9.2\5.9.2\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG119110 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG119111 DB	'qRegisterNormalizedMetaType', 00H
$SG118505 DB	'C:\Qt\Qt5.9.2\5.9.2\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG118506 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG118507 DB	'qRegisterNormalizedMetaType', 00H
$SG120758 DB	'C:\Qt\Qt5.9.2\5.9.2\msvc2015\include\QtCore/qmetatype.h', 00H
	ORG $+4
$SG120759 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG120760 DB	'qRegisterNormalizedMetaType', 00H
?qt_meta_stringdata_Highlighter@@3Uqt_meta_stringdata_Highlighter_t@@B DD 0ffffffffH ; qt_meta_stringdata_Highlighter
	DD	0bH
	DD	00H
	DD	010H
	DB	'Highlighter', 00H
?qt_meta_data_Highlighter@@3QBIB DD 07H			; qt_meta_data_Highlighter
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Highlighter@@UBEPBUQMetaObject@@XZ	; Highlighter::metaObject
PUBLIC	?qt_metacast@Highlighter@@UAEPAXPBD@Z		; Highlighter::qt_metacast
PUBLIC	?qt_metacall@Highlighter@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; Highlighter::qt_metacall
PUBLIC	?qt_static_metacall@Highlighter@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; Highlighter::qt_static_metacall
PUBLIC	?staticMetaObject@Highlighter@@2UQMetaObject@@B	; Highlighter::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QSyntaxHighlighter@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QSyntaxHighlighter@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QSyntaxHighlighter@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Highlighter@@2UQMetaObject@@B DB 018H DUP (?) ; Highlighter::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Highlighter@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@Highlighter@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Highlighter@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Highlighter@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Highlighter@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Highlighter::staticMetaObject'', COMDAT
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 68
	push	ebp
	mov	ebp, esp
; Line 66
	mov	eax, DWORD PTR __imp_?staticMetaObject@QSyntaxHighlighter@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B, eax
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_Highlighter@@3Uqt_meta_stringdata_Highlighter_t@@B
; Line 67
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_Highlighter@@3QBIB
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@Highlighter@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; Highlighter::qt_static_metacall
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B+16, 0
	mov	DWORD PTR ?staticMetaObject@Highlighter@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@Highlighter@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Highlighter::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@Highlighter@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; Highlighter::qt_static_metacall
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 58
	push	ebp
	mov	ebp, esp
; Line 63
	pop	ebp
	ret	0
?qt_static_metacall@Highlighter@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; Highlighter::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@Highlighter@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; Highlighter::qt_metacall
; _this$ = ecx
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 85
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 86
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QSyntaxHighlighter@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 87
	mov	eax, DWORD PTR __id$[ebp]
; Line 88
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@Highlighter@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; Highlighter::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@Highlighter@@UAEPAXPBD@Z PROC		; Highlighter::qt_metacast
; _this$ = ecx
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 78
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 79
	push	OFFSET ?qt_meta_stringdata_Highlighter@@3Uqt_meta_stringdata_Highlighter_t@@B+16
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 80
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 81
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QSyntaxHighlighter@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 82
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@Highlighter@@UAEPAXPBD@Z ENDP		; Highlighter::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@Highlighter@@UBEPBUQMetaObject@@XZ PROC	; Highlighter::metaObject
; _this$ = ecx
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 72
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 73
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@Highlighter@@2UQMetaObject@@B ; Highlighter::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 74
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@Highlighter@@UBEPBUQMetaObject@@XZ ENDP	; Highlighter::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File c:\qt\qt5.9.2\5.9.2\msvc2015\include\qtcore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 91
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File e:\young\project\myplot\qtguiapplication3\qtguiapplication3\generatedfiles\debug\moc_highlighter.cpp
; Line 91
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
